import type {
  ActivityItem,
  Approval,
  AuditEvent,
  Campaign,
  ContentPiece,
  Cost,
  ExitReadiness,
  Incident,
  Metric,
  Opportunity,
  Report,
  VoiceBriefing,
} from "@/types";

export const metrics: Metric[] = [
  { id: "m1", label: "Ingresos totales", value: "3.340 USD", delta: 18.4, period: "vs mes anterior", state: "ok", href: "/finanzas", icon: "revenue" },
  { id: "m2", label: "Usuarios activos", value: "528", delta: 12.1, period: "vs mes anterior", state: "ok", href: "/portafolio", icon: "users" },
  { id: "m3", label: "Aplicaciones activas", value: "3", delta: 0, period: "sin cambios", state: "ok", href: "/portafolio", icon: "apps" },
  { id: "m4", label: "Agentes ejecutándose", value: "2", delta: -1, period: "vs ayer", state: "ok", href: "/agentes", icon: "agents" },
  { id: "m5", label: "Tareas pendientes", value: "14", delta: 4, period: "vs semana anterior", state: "warn", href: "/departamentos", icon: "tasks" },
  { id: "m6", label: "Costos de IA del mes", value: "1.284 USD", delta: -8.7, period: "vs mes anterior", state: "ok", href: "/finanzas", icon: "ai" },
  { id: "m7", label: "Incidentes críticos", value: "1", delta: 1, period: "vs semana anterior", state: "risk", href: "/portafolio", icon: "incident" },
  { id: "m8", label: "Aprobaciones pendientes", value: "5", delta: 2, period: "vs ayer", state: "warn", href: "/aprobaciones", icon: "approval" },
];

export const approvals: Approval[] = [
  {
    id: "ap-1",
    title: "Presupuesto de marketing App 02",
    proposal: "Asignar 1.200 USD para el experimento de adquisición de agosto.",
    reason: "El experimento anterior obtuvo un costo por lead de 4,10 USD, por debajo del objetivo.",
    benefit: "Estimación de 260-300 leads adicionales para la beta.",
    requestedBy: "GrowthOps",
    productId: "app-02",
    departmentId: "mkt",
    risk: "medio",
    cost: 1200,
    bucket: "urgente",
    recommendation: "Aprobar con seguimiento semanal del costo por lead.",
    approver: "ceo",
    deadline: "hoy 18:00",
    evidence: ["Reporte de campaña julio", "Cálculo de CPL", "Comparativa de canales"],
    state: "pendiente",
  },
  {
    id: "ap-2",
    title: "Acceso a modelo de mayor contexto",
    proposal: "Habilitar un modelo de contexto extendido para el análisis de entrevistas.",
    reason: "Las transcripciones exceden el límite del modelo actual y se pierden fragmentos.",
    benefit: "Análisis completo sin fragmentar entrevistas.",
    requestedBy: "InsightAI",
    productId: "app-02",
    departmentId: "venture",
    risk: "medio",
    cost: 185,
    bucket: "urgente",
    recommendation: "Aprobar con límite mensual de gasto.",
    approver: "ceo",
    deadline: "hoy 20:00",
    evidence: ["Traza de truncado", "Estimación de costo mensual"],
    state: "pendiente",
  },
  {
    id: "ap-3",
    title: "Publicación de 3 piezas de contenido",
    proposal: "Publicar 3 piezas para el canal faceless de YouTube esta semana.",
    reason: "Calendario editorial con hueco en martes y jueves.",
    benefit: "Mantener cadencia de publicación y crecimiento de lista de espera.",
    requestedBy: "NovaContent",
    productId: "app-02",
    departmentId: "dist",
    risk: "bajo",
    cost: 0,
    bucket: "hoy",
    recommendation: "Aprobar tras revisión editorial de la directora de distribución.",
    approver: "distribucion",
    deadline: "hoy 22:00",
    evidence: ["Guiones v2", "Miniaturas propuestas"],
    state: "pendiente",
  },
  {
    id: "ap-4",
    title: "Infraestructura adicional App 01",
    proposal: "Escalar la base de datos al siguiente nivel de plan.",
    reason: "El uso de conexiones alcanzó el 82% durante la beta.",
    benefit: "Evitar degradación en la beta cerrada.",
    requestedBy: "CodePilot",
    productId: "app-01",
    departmentId: "eng",
    risk: "bajo",
    cost: 74,
    bucket: "semana",
    recommendation: "Aprobar antes del cierre de beta.",
    approver: "ceo",
    deadline: "21 ago 2026",
    evidence: ["Métricas de conexiones", "Comparativa de planes"],
    state: "pendiente",
  },
  {
    id: "ap-5",
    title: "Alianza de distribución LATAM",
    proposal: "Firmar acuerdo de co-marketing sin costo con una comunidad de retail.",
    reason: "La comunidad tiene 8.400 miembros del segmento objetivo.",
    benefit: "Acceso a audiencia cualificada sin inversión directa.",
    requestedBy: "DealDesk",
    productId: "app-01",
    departmentId: "sales",
    risk: "bajo",
    cost: 0,
    bucket: "semana",
    recommendation: "Aprobar con revisión legal del acuerdo.",
    approver: "ceo",
    deadline: "24 ago 2026",
    evidence: ["Borrador de acuerdo", "Perfil de la comunidad"],
    state: "pendiente",
  },
  {
    id: "ap-6",
    title: "Cambio de proveedor de correo transaccional",
    proposal: "Migrar el envío transaccional a un proveedor con mejor entregabilidad.",
    reason: "Tasa de entrega actual del 94,2%.",
    benefit: "Mejor entregabilidad en la beta.",
    requestedBy: "CodePilot",
    productId: "app-01",
    departmentId: "eng",
    risk: "bajo",
    cost: 29,
    bucket: "informativa",
    recommendation: "Informativo: no requiere acción inmediata.",
    approver: "ceo",
    deadline: "31 ago 2026",
    evidence: ["Reporte de entregabilidad"],
    state: "pendiente",
  },
  {
    id: "ap-7",
    title: "Aumento de créditos de voz",
    proposal: "Revisar el consumo de créditos de voz del mes.",
    reason: "El consumo alcanzó el 76% del límite mensual.",
    benefit: "Continuidad de los briefings de voz.",
    requestedBy: "LedgerBot",
    productId: null,
    departmentId: "fin",
    risk: "medio",
    cost: 0,
    bucket: "hoy",
    recommendation: "Decisión exclusiva del fundador. No se compran créditos automáticamente.",
    approver: "ceo",
    deadline: "hoy 23:00",
    evidence: ["Detalle de consumo mensual"],
    state: "pendiente",
  },
  {
    id: "ap-8",
    title: "Contratación de perfil de datos",
    proposal: "Abrir proceso para un perfil de datos a tiempo parcial.",
    reason: "Carga de trabajo de ingesta creciente.",
    benefit: "Reducción de tareas manuales de datos.",
    requestedBy: "DataScout",
    productId: null,
    departmentId: "intel",
    risk: "medio",
    cost: 900,
    bucket: "resuelta",
    recommendation: "Se solicitaron cambios: reducir alcance a proyecto puntual.",
    approver: "ceo",
    deadline: "14 ago 2026",
    evidence: ["Estimación de horas"],
    state: "cambios",
  },
];

export const activity: ActivityItem[] = [
  { id: "a1", agent: "FlowSmith", departmentId: "product", action: "Inició especificación del flujo de trazabilidad", productId: "app-03", result: "En curso", time: "10:38", state: "en_curso", runId: "run-1045" },
  { id: "a2", agent: "NovaContent", departmentId: "dist", action: "Preparó 3 piezas para revisión editorial", productId: "app-02", result: "Esperando aprobación", time: "10:31", state: "alerta", runId: "run-1042" },
  { id: "a3", agent: "MarketMind", departmentId: "intel", action: "Generó reporte de tendencias de mercado", productId: "app-01", result: "Completado", time: "10:22", state: "completado", runId: "run-1041" },
  { id: "a4", agent: "CodePilot", departmentId: "eng", action: "Implementó módulo de autenticación SSO", productId: "app-01", result: "PR #218 abierta", time: "09:58", state: "completado", runId: "run-1042" },
  { id: "a5", agent: "InsightAI", departmentId: "venture", action: "Detectó anomalía en métricas de retención", productId: "app-02", result: "Alerta emitida", time: "09:41", state: "alerta", runId: "run-1043" },
  { id: "a6", agent: "DataScout", departmentId: "intel", action: "Sincronizó 3 fuentes de datos nuevas", productId: "app-01", result: "Completado", time: "09:15", state: "completado", runId: "run-1041" },
  { id: "a7", agent: "SentryQA", departmentId: "qa", action: "Ejecutó suite de regresión completa", productId: "app-02", result: "2 fallos menores", time: "08:47", state: "completado", runId: "run-1042" },
  { id: "a8", agent: "ExitPrep", departmentId: "exit", action: "Intentó auditar documentación legal", productId: "app-01", result: "Error de permisos", time: "07:12", state: "error", runId: "run-1044" },
];

export const costs: Cost[] = [
  { id: "c1", category: "Modelos de IA", productId: "app-01", amount: 462, month: "Ago 2026" },
  { id: "c2", category: "Modelos de IA", productId: "app-02", amount: 388, month: "Ago 2026" },
  { id: "c3", category: "Modelos de IA", productId: "app-03", amount: 144, month: "Ago 2026" },
  { id: "c4", category: "Hosting", productId: "app-01", amount: 148, month: "Ago 2026" },
  { id: "c5", category: "Hosting", productId: "app-02", amount: 96, month: "Ago 2026" },
  { id: "c6", category: "Hosting", productId: "app-03", amount: 54, month: "Ago 2026" },
  { id: "c7", category: "Software", productId: null, amount: 212, month: "Ago 2026" },
  { id: "c8", category: "Voz y audio", productId: null, amount: 118, month: "Ago 2026" },
];

export const burnSeries = [
  { label: "Mar", ingresos: 320, costos: 980 },
  { label: "Abr", ingresos: 760, costos: 1120 },
  { label: "May", ingresos: 1260, costos: 1340 },
  { label: "Jun", ingresos: 1930, costos: 1490 },
  { label: "Jul", ingresos: 2650, costos: 1580 },
  { label: "Ago", ingresos: 3340, costos: 1622 },
];

export const incidents: Incident[] = [
  { id: "i1", title: "Caída de retención en cohorte semana 3 (App 02)", productId: "app-02", severity: "critica", state: "abierta", openedAt: "hoy 09:41" },
  { id: "i2", title: "Acceso denegado a carpeta legal (App 01)", productId: "app-01", severity: "alta", state: "abierta", openedAt: "hoy 07:12" },
  { id: "i3", title: "Latencia elevada en informes (App 01)", productId: "app-01", severity: "media", state: "mitigada", openedAt: "ayer 21:04" },
];

export const reports: Report[] = [
  { id: "rep-2201", title: "Tendencias de mercado Q3", departmentId: "intel", author: "MarketMind", date: "17 ago 2026", summary: "Tres competidores ajustaron precios a la baja; oportunidad en el segmento de retail independiente.", type: "Mercado" },
  { id: "rep-2202", title: "Cohortes de retención App 02", departmentId: "venture", author: "InsightAI", date: "17 ago 2026", summary: "La cohorte de la semana 3 cae 14 puntos frente a la media; se investiga onboarding.", type: "Métricas" },
  { id: "rep-2203", title: "Regresión previa a beta App 01", departmentId: "qa", author: "SentryQA", date: "17 ago 2026", summary: "Suite completa con 2 fallos menores en exportación de informes.", type: "Calidad" },
  { id: "rep-2204", title: "Rendimiento de contenido semanal", departmentId: "dist", author: "NovaContent", date: "16 ago 2026", summary: "El canal faceless duplicó la retención media de vista respecto a la semana anterior.", type: "Distribución" },
  { id: "rep-2205", title: "Consolidado de costos agosto", departmentId: "fin", author: "LedgerBot", date: "17 ago 2026", summary: "Costos de IA a la baja 8,7% por cambio de modelo en tareas de resumen.", type: "Finanzas" },
];

export const auditEvents: AuditEvent[] = [
  { id: "ae1", at: "hoy 10:38", actor: "Joshua R. García", action: "Ejecutó manualmente FlowSmith", target: "app-03" },
  { id: "ae2", at: "hoy 09:41", actor: "Sistema", action: "Creó incidente crítico", target: "app-02" },
  { id: "ae3", at: "hoy 08:12", actor: "Ana García", action: "Revisó calendario editorial", target: "distribución" },
  { id: "ae4", at: "ayer 18:40", actor: "Joshua R. García", action: "Solicitó cambios en aprobación ap-8", target: "aprobaciones" },
];

export const voiceBriefings: VoiceBriefing[] = [
  { id: "vb1", assistant: "ZADAR", title: "Briefing ejecutivo matutino", date: "17 ago 2026 · 07:30", duration: "4 min 12 s", topics: ["Portafolio", "Riesgos", "Aprobaciones"], summary: "Tres aplicaciones activas; una anomalía crítica en retención de App 02 y cinco aprobaciones pendientes." },
  { id: "vb2", assistant: "NOVA", title: "Briefing de distribución", date: "17 ago 2026 · 08:15", duration: "3 min 05 s", topics: ["Contenido", "Comunidad", "Campañas"], summary: "Cadencia editorial al día; tres piezas esperan revisión y la comunidad creció 6% semanal." },
  { id: "vb3", assistant: "ZADAR", title: "Cierre financiero semanal", date: "16 ago 2026 · 19:00", duration: "5 min 40 s", topics: ["Costos", "Burn", "Runway"], summary: "Costos de IA a la baja; runway estimado en 11 meses con burn actual." },
  { id: "vb4", assistant: "NOVA", title: "Resumen de experimentos", date: "15 ago 2026 · 18:30", duration: "2 min 48 s", topics: ["Experimentos", "Conversión"], summary: "El experimento de LinkedIn superó el objetivo de costo por lead; pendiente presupuesto de agosto." },
];

export const opportunities: Opportunity[] = [
  {
    id: "op-1",
    name: "Gestión de turnos para clínicas pequeñas",
    stage: "idea_capturada",
    problem: "Las clínicas pequeñas gestionan turnos por mensajería y pierden citas.",
    idealCustomer: "Clínicas de 1 a 4 profesionales en LATAM.",
    solution: "Agenda con recordatorios automáticos y lista de espera inteligente.",
    competitors: ["Agendapp", "MediTurno"],
    differentiation: "Configuración sin equipo técnico y precio local.",
    market: "México, Colombia",
    size: "Mediana",
    complexity: "baja",
    estimatedTime: "10 semanas",
    regulatoryRisk: "medio",
    monetization: "Suscripción mensual por profesional",
    evidence: ["6 conversaciones exploratorias"],
    score: 62,
    recommendation: "Continuar investigación antes de comprometer recursos.",
  },
  {
    id: "op-2",
    name: "Panel de cumplimiento para exportadores",
    stage: "investigacion",
    problem: "Los exportadores no tienen visibilidad de requisitos cambiantes.",
    idealCustomer: "Exportadores agrícolas medianos.",
    solution: "Panel de cumplimiento con alertas normativas.",
    competitors: ["TraceOne"],
    differentiation: "Enfoque LATAM con normativa europea.",
    market: "Colombia, Perú",
    size: "Grande",
    complexity: "alta",
    estimatedTime: "20 semanas",
    regulatoryRisk: "alto",
    monetization: "Suscripción anual + implementación",
    evidence: ["Investigación regulatoria", "3 entrevistas"],
    score: 71,
    recommendation: "Mantener como extensión de App 03, no como producto separado.",
  },
  {
    id: "op-3",
    name: "Analítica para tiendas de barrio",
    stage: "problema_validado",
    problem: "Sin datos de rotación, las tiendas compran mal el inventario.",
    idealCustomer: "Tiendas con 1 punto de venta.",
    solution: "Recomendación de compra semanal desde tickets.",
    competitors: ["ShopSense"],
    differentiation: "Funciona con ticket fotografiado.",
    market: "México",
    size: "Grande",
    complexity: "media",
    estimatedTime: "14 semanas",
    regulatoryRisk: "bajo",
    monetization: "Suscripción baja de alto volumen",
    evidence: ["14 entrevistas", "Prueba de concepto"],
    score: 78,
    recommendation: "Priorizar tras el lanzamiento de App 01.",
  },
  {
    id: "op-4",
    name: "Portal de reputación para restaurantes",
    stage: "mercado_validado",
    problem: "Las reseñas se dispersan y no se responden a tiempo.",
    idealCustomer: "Restaurantes con 2 a 10 locales.",
    solution: "Bandeja unificada con respuestas sugeridas.",
    competitors: ["ReviewHub", "Localy"],
    differentiation: "Respuestas alineadas al tono de la marca.",
    market: "España, México",
    size: "Mediana",
    complexity: "media",
    estimatedTime: "12 semanas",
    regulatoryRisk: "bajo",
    monetization: "Suscripción por local",
    evidence: ["21 entrevistas", "Lista de espera de 90"],
    score: 81,
    recommendation: "Candidata al siguiente ciclo de incubación.",
  },
  {
    id: "op-5",
    name: "Asistente de cobros para autónomos",
    stage: "aprobada",
    problem: "Los autónomos pierden ingresos por facturas no cobradas.",
    idealCustomer: "Autónomos y microempresas de servicios.",
    solution: "Seguimiento automático de cobros con recordatorios.",
    competitors: ["Cobralo"],
    differentiation: "Integración con facturación local.",
    market: "España",
    size: "Mediana",
    complexity: "baja",
    estimatedTime: "8 semanas",
    regulatoryRisk: "medio",
    monetization: "Suscripción mensual",
    evidence: ["18 entrevistas", "Carta de intención"],
    score: 84,
    recommendation: "Aprobada para construcción tras la beta de App 01.",
  },
  {
    id: "op-6",
    name: "Marketplace de cursos técnicos",
    stage: "archivada",
    problem: "Oferta fragmentada de formación técnica.",
    idealCustomer: "Estudiantes técnicos.",
    solution: "Marketplace curado.",
    competitors: ["Muchos"],
    differentiation: "Insuficiente.",
    market: "LATAM",
    size: "Grande",
    complexity: "alta",
    estimatedTime: "24 semanas",
    regulatoryRisk: "bajo",
    monetization: "Comisión",
    evidence: ["Análisis competitivo"],
    score: 34,
    recommendation: "Archivada: mercado saturado y diferenciación débil.",
  },
];

export const contentPieces: ContentPiece[] = [
  { id: "cp1", title: "Cómo predecir el inventario sin analista", channel: "YouTube faceless", productId: "app-01", state: "programado", date: "18 ago 2026", owner: "NovaContent", reach: 0 },
  { id: "cp2", title: "3 errores de atención al cliente en pymes", channel: "YouTube faceless", productId: "app-02", state: "revision", date: "19 ago 2026", owner: "NovaContent", reach: 0 },
  { id: "cp3", title: "Detrás de la beta de Lumen Retail", channel: "Newsletter", productId: "app-01", state: "produccion", date: "20 ago 2026", owner: "Ana García", reach: 0 },
  { id: "cp4", title: "Trazabilidad explicada en 60 segundos", channel: "TikTok", productId: "app-03", state: "guion", date: "21 ago 2026", owner: "NovaContent", reach: 0 },
  { id: "cp5", title: "Preguntas de la comunidad · agosto", channel: "Comunidad", productId: null, state: "idea", date: "22 ago 2026", owner: "CommunityOps", reach: 0 },
  { id: "cp6", title: "Caso: 12 pilotos en 6 semanas", channel: "LinkedIn", productId: "app-01", state: "publicado", date: "14 ago 2026", owner: "Ana García", reach: 4820 },
  { id: "cp7", title: "Por qué medimos retención semanal", channel: "Newsletter", productId: "app-02", state: "publicado", date: "12 ago 2026", owner: "Ana García", reach: 1240 },
  { id: "cp8", title: "Demo silenciosa del panel", channel: "YouTube faceless", productId: "app-01", state: "publicado", date: "10 ago 2026", owner: "NovaContent", reach: 9310 },
];

export const campaigns: Campaign[] = [
  { id: "cm1", name: "Beta cerrada Lumen", channel: "LinkedIn", productId: "app-01", state: "activa", budget: 800, spent: 512, leads: 128, conversion: 6.4 },
  { id: "cm2", name: "Lista de espera Atenea", channel: "YouTube faceless", productId: "app-02", state: "activa", budget: 400, spent: 268, leads: 96, conversion: 4.1 },
  { id: "cm3", name: "Alianzas agro", channel: "Eventos", productId: "app-03", state: "planificada", budget: 300, spent: 0, leads: 0, conversion: 0 },
  { id: "cm4", name: "Retargeting julio", channel: "Meta", productId: "app-01", state: "finalizada", budget: 350, spent: 350, leads: 74, conversion: 3.2 },
];

export const channelPerformance = [
  { canal: "YouTube", alcance: 9310, leads: 96 },
  { canal: "LinkedIn", alcance: 4820, leads: 128 },
  { canal: "Newsletter", alcance: 1240, leads: 41 },
  { canal: "TikTok", alcance: 2180, leads: 22 },
  { canal: "Comunidad", alcance: 860, leads: 18 },
];

export const funnel = [
  { etapa: "Visitantes", valor: 12400 },
  { etapa: "Registros", valor: 1180 },
  { etapa: "Activados", valor: 528 },
  { etapa: "Pagos", valor: 46 },
];

export const exitReadiness: ExitReadiness[] = [
  {
    productId: "app-01",
    score: 64,
    items: [
      { label: "Calidad del código", value: 74, note: "Deuda acotada, revisión continua." },
      { label: "Documentación", value: 68, note: "Falta manual operativo completo." },
      { label: "Pruebas", value: 71, note: "Objetivo 80% de cobertura." },
      { label: "Seguridad", value: 78, note: "Sin hallazgos críticos abiertos." },
      { label: "Propiedad intelectual", value: 40, note: "Carpeta legal inaccesible." },
      { label: "Dependencias", value: 66, note: "2 licencias por revisar." },
      { label: "Métricas", value: 72, note: "Serie histórica de 6 meses." },
      { label: "Finanzas", value: 70, note: "Margen del 69%." },
      { label: "Contratos", value: 55, note: "12 pilotos sin contrato marco." },
      { label: "Datos", value: 62, note: "Política de retención pendiente." },
      { label: "Infraestructura", value: 75, note: "Despliegue reproducible." },
      { label: "Manuales operativos", value: 48, note: "En redacción." },
      { label: "Riesgos", value: 60, note: "2 riesgos medios activos." },
    ],
    dataRoom: [
      { label: "Estados financieros", state: "parcial" },
      { label: "Contratos de clientes", state: "pendiente" },
      { label: "Arquitectura técnica", state: "listo" },
      { label: "Registro de marca", state: "pendiente" },
      { label: "Política de datos", state: "parcial" },
    ],
  },
  {
    productId: "app-02",
    score: 41,
    items: [
      { label: "Calidad del código", value: 52, note: "Prototipo en consolidación." },
      { label: "Documentación", value: 44, note: "Especificación parcial." },
      { label: "Pruebas", value: 48, note: "Cobertura baja." },
      { label: "Seguridad", value: 58, note: "Revisión inicial hecha." },
      { label: "Propiedad intelectual", value: 35, note: "Sin registro de marca." },
      { label: "Dependencias", value: 60, note: "Sin licencias restrictivas." },
      { label: "Métricas", value: 46, note: "Series cortas." },
      { label: "Finanzas", value: 32, note: "Margen del 31%." },
      { label: "Contratos", value: 20, note: "Sin contratos firmados." },
      { label: "Datos", value: 40, note: "Modelo de datos en cambio." },
      { label: "Infraestructura", value: 50, note: "Entorno único." },
      { label: "Manuales operativos", value: 25, note: "No iniciados." },
      { label: "Riesgos", value: 38, note: "1 riesgo alto activo." },
    ],
    dataRoom: [
      { label: "Estados financieros", state: "parcial" },
      { label: "Contratos de clientes", state: "pendiente" },
      { label: "Arquitectura técnica", state: "parcial" },
      { label: "Registro de marca", state: "pendiente" },
      { label: "Política de datos", state: "pendiente" },
    ],
  },
  {
    productId: "app-03",
    score: 29,
    items: [
      { label: "Calidad del código", value: 30, note: "Base inicial." },
      { label: "Documentación", value: 52, note: "Marco regulatorio documentado." },
      { label: "Pruebas", value: 22, note: "Sin suite estable." },
      { label: "Seguridad", value: 40, note: "Pendiente revisión formal." },
      { label: "Propiedad intelectual", value: 30, note: "Sin registro." },
      { label: "Dependencias", value: 55, note: "Stack mínimo." },
      { label: "Métricas", value: 10, note: "Sin usuarios todavía." },
      { label: "Finanzas", value: 12, note: "Sin ingresos." },
      { label: "Contratos", value: 25, note: "3 cartas de intención." },
      { label: "Datos", value: 28, note: "Modelo en diseño." },
      { label: "Infraestructura", value: 35, note: "Entorno de desarrollo." },
      { label: "Manuales operativos", value: 15, note: "No iniciados." },
      { label: "Riesgos", value: 45, note: "1 riesgo medio activo." },
    ],
    dataRoom: [
      { label: "Estados financieros", state: "pendiente" },
      { label: "Contratos de clientes", state: "pendiente" },
      { label: "Arquitectura técnica", state: "parcial" },
      { label: "Registro de marca", state: "pendiente" },
      { label: "Política de datos", state: "pendiente" },
    ],
  },
];

export const voiceUsage = { used: 76, limit: 100, label: "Créditos de voz del mes" };

export const departmentBudgetSeries = [
  { dep: "Ingeniería", usado: 520, total: 800 },
  { dep: "Distribución", usado: 320, total: 500 },
  { dep: "Marketing", usado: 410, total: 600 },
  { dep: "Producto", usado: 240, total: 450 },
  { dep: "QA", usado: 150, total: 300 },
];
