import type { Agent, AgentRun, Department, Task, Workflow, User } from "@/types";

export const users: User[] = [
  {
    id: "u1",
    name: "Joshua R. García",
    role: "ceo",
    title: "CEO / Fundador",
    initials: "JG",
    assistant: "ZADAR",
  },
  {
    id: "u2",
    name: "Ana García",
    role: "distribucion",
    title: "Directora de distribución",
    initials: "AG",
    assistant: "NOVA",
  },
];

export const departments: Department[] = [
  {
    id: "intel",
    name: "Inteligencia competitiva",
    objective: "Monitorear competidores, precios y señales de mercado cada semana.",
    agents: ["MarketMind", "DataScout"],
    openTasks: 4,
    doneTasks: 38,
    blockers: 0,
    budgetUsed: 210,
    budgetTotal: 400,
    quality: 88,
    lastActivity: "hace 22 min",
    accent: "violet",
  },
  {
    id: "venture",
    name: "Venture y validación",
    objective: "Validar problema, mercado y disposición a pagar antes de construir.",
    agents: ["InsightAI"],
    openTasks: 6,
    doneTasks: 21,
    blockers: 1,
    budgetUsed: 180,
    budgetTotal: 350,
    quality: 79,
    lastActivity: "hace 1 h",
    accent: "blue",
  },
  {
    id: "intl",
    name: "Oportunidades internacionales",
    objective: "Detectar mercados con demanda y baja fricción regulatoria.",
    agents: ["DataScout"],
    openTasks: 2,
    doneTasks: 9,
    blockers: 0,
    budgetUsed: 60,
    budgetTotal: 200,
    quality: 74,
    lastActivity: "ayer",
    accent: "violet",
  },
  {
    id: "product",
    name: "Producto y diseño",
    objective: "Definir alcance, flujos y sistema de diseño de cada aplicación.",
    agents: ["FlowSmith"],
    openTasks: 9,
    doneTasks: 44,
    blockers: 2,
    budgetUsed: 240,
    budgetTotal: 450,
    quality: 84,
    lastActivity: "hace 40 min",
    accent: "blue",
  },
  {
    id: "eng",
    name: "Ingeniería",
    objective: "Construir y desplegar producto con calidad sostenible.",
    agents: ["CodePilot"],
    openTasks: 12,
    doneTasks: 96,
    blockers: 1,
    budgetUsed: 520,
    budgetTotal: 800,
    quality: 86,
    lastActivity: "hace 8 min",
    accent: "blue",
  },
  {
    id: "qa",
    name: "QA y seguridad",
    objective: "Detectar regresiones, vulnerabilidades y deuda crítica.",
    agents: ["SentryQA"],
    openTasks: 7,
    doneTasks: 52,
    blockers: 0,
    budgetUsed: 150,
    budgetTotal: 300,
    quality: 91,
    lastActivity: "hace 2 h",
    accent: "green",
  },
  {
    id: "dist",
    name: "Distribución y comunidad",
    objective: "Construir audiencia propia y comunidad activa por producto.",
    agents: ["NovaContent", "CommunityOps"],
    openTasks: 11,
    doneTasks: 63,
    blockers: 1,
    budgetUsed: 320,
    budgetTotal: 500,
    quality: 82,
    lastActivity: "hace 15 min",
    accent: "violet",
  },
  {
    id: "mkt",
    name: "Marketing",
    objective: "Ejecutar campañas medibles con costo por lead controlado.",
    agents: ["GrowthOps"],
    openTasks: 5,
    doneTasks: 34,
    blockers: 0,
    budgetUsed: 410,
    budgetTotal: 600,
    quality: 77,
    lastActivity: "hace 3 h",
    accent: "amber",
  },
  {
    id: "sales",
    name: "Ventas",
    objective: "Convertir pilotos en contratos recurrentes.",
    agents: ["DealDesk"],
    openTasks: 4,
    doneTasks: 17,
    blockers: 0,
    budgetUsed: 90,
    budgetTotal: 250,
    quality: 73,
    lastActivity: "ayer",
    accent: "blue",
  },
  {
    id: "fin",
    name: "Finanzas y operaciones",
    objective: "Controlar burn, márgenes y costos de IA por producto.",
    agents: ["LedgerBot"],
    openTasks: 3,
    doneTasks: 28,
    blockers: 0,
    budgetUsed: 70,
    budgetTotal: 200,
    quality: 90,
    lastActivity: "hace 5 h",
    accent: "green",
  },
  {
    id: "exit",
    name: "Preparación para adquisición",
    objective: "Mantener cada producto vendible: documentación, datos y contratos.",
    agents: ["ExitPrep"],
    openTasks: 6,
    doneTasks: 11,
    blockers: 2,
    budgetUsed: 40,
    budgetTotal: 150,
    quality: 68,
    lastActivity: "hace 2 d",
    accent: "amber",
  },
];

export const agents: Agent[] = [
  {
    id: "marketmind",
    name: "MarketMind",
    role: "Analista de mercado",
    departmentId: "intel",
    description: "Genera reportes de tendencias y movimientos de competidores a partir de fuentes públicas.",
    capabilities: ["Análisis de tendencias", "Comparativa de precios", "Resumen ejecutivo"],
    tools: ["Búsqueda web", "Lector de documentos", "Generador de reportes"],
    products: ["app-01", "app-02"],
    status: "disponible",
    currentTask: null,
    lastRun: "hoy 10:22",
    nextRun: "lunes 08:00",
    accumulatedCost: 84.2,
    riskLevel: "bajo",
  },
  {
    id: "datascout",
    name: "DataScout",
    role: "Recolector de datos",
    departmentId: "intel",
    description: "Sincroniza fuentes de datos externas y normaliza la información para otros agentes.",
    capabilities: ["Ingesta de fuentes", "Normalización", "Detección de duplicados"],
    tools: ["HTTP fetch", "Parser CSV", "Almacén de documentos"],
    products: ["app-01", "app-03"],
    status: "programado",
    currentTask: null,
    lastRun: "hoy 09:15",
    nextRun: "hoy 18:00",
    accumulatedCost: 41.8,
    riskLevel: "bajo",
  },
  {
    id: "insightai",
    name: "InsightAI",
    role: "Analista de validación",
    departmentId: "venture",
    description: "Procesa entrevistas y encuestas para evaluar problema, mercado y precio.",
    capabilities: ["Análisis cualitativo", "Segmentación", "Detección de anomalías"],
    tools: ["Transcripción", "Análisis de texto", "Generador de reportes"],
    products: ["app-02"],
    status: "esperando_aprobacion",
    currentTask: "Solicita acceso a modelo de mayor contexto",
    lastRun: "hoy 09:41",
    nextRun: "pendiente de aprobación",
    accumulatedCost: 63.5,
    riskLevel: "medio",
  },
  {
    id: "flowsmith",
    name: "FlowSmith",
    role: "Diseñador de flujos",
    departmentId: "product",
    description: "Traduce requisitos en flujos, estados y especificaciones de pantalla.",
    capabilities: ["Mapas de flujo", "Especificación de UI", "Revisión de consistencia"],
    tools: ["Generador de especificaciones", "Lector de diseño"],
    products: ["app-01", "app-03"],
    status: "ejecutando",
    currentTask: "Especificando flujo de trazabilidad de lote (App 03)",
    lastRun: "hoy 10:38",
    nextRun: "al finalizar tarea",
    accumulatedCost: 57.1,
    riskLevel: "bajo",
  },
  {
    id: "codepilot",
    name: "CodePilot",
    role: "Ingeniero de implementación",
    departmentId: "eng",
    description: "Implementa módulos acotados con pruebas y abre solicitudes de revisión.",
    capabilities: ["Implementación de módulos", "Pruebas unitarias", "Refactor acotado"],
    tools: ["Repositorio", "Ejecutor de pruebas", "CI"],
    products: ["app-01", "app-02"],
    status: "ejecutando",
    currentTask: "Módulo de facturación recurrente (App 01)",
    lastRun: "hoy 09:58",
    nextRun: "al finalizar tarea",
    accumulatedCost: 212.4,
    riskLevel: "medio",
  },
  {
    id: "sentryqa",
    name: "SentryQA",
    role: "Verificador de calidad",
    departmentId: "qa",
    description: "Ejecuta suites de pruebas y revisiones de seguridad sobre cada despliegue.",
    capabilities: ["Pruebas de regresión", "Análisis estático", "Revisión de dependencias"],
    tools: ["Ejecutor de pruebas", "Escáner de dependencias"],
    products: ["app-01", "app-02", "app-03"],
    status: "disponible",
    currentTask: null,
    lastRun: "hoy 08:47",
    nextRun: "tras próximo despliegue",
    accumulatedCost: 96.3,
    riskLevel: "bajo",
  },
  {
    id: "novacontent",
    name: "NovaContent",
    role: "Productor de contenido",
    departmentId: "dist",
    description: "Prepara guiones y piezas para canales de distribución; requiere aprobación antes de publicar.",
    capabilities: ["Guiones", "Copy multicanal", "Calendario editorial"],
    tools: ["Generador de texto", "Planificador", "Biblioteca de marca"],
    products: ["app-01", "app-02"],
    status: "esperando_aprobacion",
    currentTask: "3 piezas listas para revisión editorial",
    lastRun: "hoy 10:31",
    nextRun: "tras aprobación",
    accumulatedCost: 74.9,
    riskLevel: "medio",
  },
  {
    id: "communityops",
    name: "CommunityOps",
    role: "Operador de comunidad",
    departmentId: "dist",
    description: "Resume conversaciones de comunidad y detecta temas recurrentes.",
    capabilities: ["Resumen de hilos", "Detección de temas", "Priorización de respuestas"],
    tools: ["Lector de foros", "Analizador de sentimiento"],
    products: ["app-02"],
    status: "disponible",
    currentTask: null,
    lastRun: "ayer 19:10",
    nextRun: "hoy 20:00",
    accumulatedCost: 28.6,
    riskLevel: "bajo",
  },
  {
    id: "growthops",
    name: "GrowthOps",
    role: "Operador de campañas",
    departmentId: "mkt",
    description: "Prepara y evalúa experimentos de adquisición con presupuesto acotado.",
    capabilities: ["Diseño de experimentos", "Cálculo de CPL", "Reportes de campaña"],
    tools: ["Analítica", "Planificador de campañas"],
    products: ["app-01", "app-02"],
    status: "bloqueado",
    currentTask: "Bloqueado: presupuesto de agosto sin aprobar",
    lastRun: "ayer 16:02",
    nextRun: "pendiente",
    accumulatedCost: 118.7,
    riskLevel: "medio",
  },
  {
    id: "dealdesk",
    name: "DealDesk",
    role: "Soporte comercial",
    departmentId: "sales",
    description: "Prepara propuestas y seguimientos para pilotos activos.",
    capabilities: ["Propuestas", "Seguimiento de pipeline", "Resumen de llamadas"],
    tools: ["CRM (lectura)", "Generador de documentos"],
    products: ["app-01"],
    status: "programado",
    currentTask: null,
    lastRun: "ayer 12:30",
    nextRun: "mañana 09:00",
    accumulatedCost: 33.2,
    riskLevel: "bajo",
  },
  {
    id: "ledgerbot",
    name: "LedgerBot",
    role: "Control financiero",
    departmentId: "fin",
    description: "Consolida costos por producto y alerta desviaciones de presupuesto.",
    capabilities: ["Consolidación de costos", "Alertas de desvío", "Proyección de burn"],
    tools: ["Hojas de cálculo", "Analítica"],
    products: ["app-01", "app-02", "app-03"],
    status: "disponible",
    currentTask: null,
    lastRun: "hoy 06:00",
    nextRun: "mañana 06:00",
    accumulatedCost: 19.4,
    riskLevel: "bajo",
  },
  {
    id: "exitprep",
    name: "ExitPrep",
    role: "Preparación de data room",
    departmentId: "exit",
    description: "Revisa documentación, contratos y dependencias necesarias para una venta.",
    capabilities: ["Auditoría documental", "Checklist de due diligence"],
    tools: ["Almacén de documentos", "Checklist"],
    products: ["app-01"],
    status: "error",
    currentTask: "Error: documento de propiedad intelectual no accesible",
    lastRun: "hoy 07:12",
    nextRun: "requiere intervención",
    accumulatedCost: 12.1,
    riskLevel: "alto",
  },
];

export const agentRuns: AgentRun[] = [
  {
    id: "run-1041",
    agentId: "marketmind",
    objective: "Generar reporte de tendencias de mercado para App 01 y App 02.",
    startedAt: "hoy 10:14",
    duration: "8 min 12 s",
    status: "completado",
    inputs: ["Lista de competidores", "Fuentes públicas autorizadas", "Reporte anterior"],
    steps: [
      { label: "Recolección de fuentes", state: "ok" },
      { label: "Normalización de datos", state: "ok" },
      { label: "Análisis comparativo", state: "ok" },
      { label: "Redacción del reporte", state: "ok" },
    ],
    outputs: ["Reporte de tendencias Q3", "5 señales de precio detectadas"],
    evidence: [
      { label: "Reporte generado", ref: "rep-2201" },
      { label: "Fuentes citadas (14)", ref: "src-884" },
    ],
    cost: 3.42,
    retries: 0,
    approvals: [],
    audit: [
      { at: "10:14", event: "Ejecución iniciada por horario" },
      { at: "10:22", event: "Ejecución completada" },
    ],
  },
  {
    id: "run-1042",
    agentId: "codepilot",
    objective: "Implementar módulo de autenticación SSO en App 01.",
    startedAt: "hoy 09:31",
    duration: "27 min 04 s",
    status: "completado",
    inputs: ["Especificación de FlowSmith", "Repositorio app-01"],
    steps: [
      { label: "Lectura de especificación", state: "ok" },
      { label: "Implementación", state: "ok" },
      { label: "Pruebas unitarias", state: "ok" },
      { label: "Solicitud de revisión", state: "ok" },
    ],
    outputs: ["PR #218 abierta", "6 pruebas nuevas"],
    evidence: [{ label: "Registro de pruebas", ref: "test-771" }],
    cost: 11.8,
    retries: 1,
    approvals: ["Revisión humana pendiente"],
    audit: [
      { at: "09:31", event: "Ejecución iniciada por tarea asignada" },
      { at: "09:44", event: "Reintento tras fallo de pruebas" },
      { at: "09:58", event: "Ejecución completada" },
    ],
  },
  {
    id: "run-1043",
    agentId: "insightai",
    objective: "Detectar anomalías en métricas de retención de App 02.",
    startedAt: "hoy 09:36",
    duration: "5 min 41 s",
    status: "completado",
    inputs: ["Serie de retención 30 días", "Cohortes de julio"],
    steps: [
      { label: "Carga de series", state: "ok" },
      { label: "Detección de anomalías", state: "ok" },
      { label: "Alerta emitida", state: "ok" },
    ],
    outputs: ["1 anomalía crítica en cohorte semana 3"],
    evidence: [{ label: "Gráfico de cohortes", ref: "chart-119" }],
    cost: 2.1,
    retries: 0,
    approvals: [],
    audit: [
      { at: "09:36", event: "Ejecución iniciada por evento de métricas" },
      { at: "09:41", event: "Alerta enviada a aprobaciones" },
    ],
  },
  {
    id: "run-1044",
    agentId: "exitprep",
    objective: "Auditar documentación de propiedad intelectual de App 01.",
    startedAt: "hoy 07:05",
    duration: "7 min 02 s",
    status: "fallido",
    inputs: ["Índice de data room", "Checklist de due diligence"],
    steps: [
      { label: "Lectura de índice", state: "ok" },
      { label: "Acceso a carpeta legal", state: "error" },
      { label: "Auditoría documental", state: "error" },
    ],
    outputs: [],
    evidence: [{ label: "Traza de error", ref: "err-402" }],
    cost: 0.9,
    retries: 2,
    approvals: [],
    audit: [
      { at: "07:05", event: "Ejecución iniciada por horario" },
      { at: "07:12", event: "Ejecución fallida: permiso insuficiente" },
    ],
  },
  {
    id: "run-1045",
    agentId: "flowsmith",
    objective: "Especificar flujo de trazabilidad de lote para App 03.",
    startedAt: "hoy 10:38",
    duration: "en curso",
    status: "en_curso",
    inputs: ["Requisitos regulatorios EUDR", "Sistema de diseño Verda"],
    steps: [
      { label: "Lectura de requisitos", state: "ok" },
      { label: "Definición de estados", state: "curso" },
      { label: "Especificación de pantallas", state: "curso" },
    ],
    outputs: [],
    evidence: [],
    cost: 1.4,
    retries: 0,
    approvals: [],
    audit: [{ at: "10:38", event: "Ejecución iniciada manualmente" }],
  },
];

export const tasks: Task[] = [
  { id: "t1", title: "Cerrar cobertura de pruebas al 80% (App 01)", productId: "app-01", departmentId: "qa", assignee: "SentryQA", state: "en_curso", priority: "alta", dueDate: "20 ago 2026" },
  { id: "t2", title: "Entrevistas de precio con 10 clientes (App 02)", productId: "app-02", departmentId: "venture", assignee: "InsightAI", state: "en_revision", priority: "alta", dueDate: "22 ago 2026" },
  { id: "t3", title: "Prototipo navegable de trazabilidad (App 03)", productId: "app-03", departmentId: "product", assignee: "FlowSmith", state: "en_curso", priority: "media", dueDate: "28 ago 2026" },
  { id: "t4", title: "Guion de 4 vídeos faceless (App 02)", productId: "app-02", departmentId: "dist", assignee: "NovaContent", state: "pendiente", priority: "media", dueDate: "19 ago 2026" },
  { id: "t5", title: "Revisar dependencias con licencia restrictiva", productId: "app-01", departmentId: "eng", assignee: "CodePilot", state: "pendiente", priority: "alta", dueDate: "21 ago 2026" },
  { id: "t6", title: "Consolidar costos de IA de agosto", productId: null, departmentId: "fin", assignee: "LedgerBot", state: "completada", priority: "media", dueDate: "17 ago 2026" },
  { id: "t7", title: "Recuperar acceso a carpeta legal", productId: "app-01", departmentId: "exit", assignee: "ExitPrep", state: "bloqueada", priority: "alta", dueDate: "18 ago 2026" },
  { id: "t8", title: "Experimento de adquisición LinkedIn", productId: "app-01", departmentId: "mkt", assignee: "GrowthOps", state: "bloqueada", priority: "media", dueDate: "23 ago 2026" },
];

export const workflows: Workflow[] = [
  { id: "w1", name: "Reporte semanal de mercado", trigger: "Horario · lunes 08:00", steps: ["DataScout", "MarketMind", "Reporte"], departmentId: "intel", active: true },
  { id: "w2", name: "Verificación previa a despliegue", trigger: "Evento · nuevo build", steps: ["SentryQA", "Aprobación humana", "Despliegue"], departmentId: "qa", active: true },
  { id: "w3", name: "Producción de contenido semanal", trigger: "Horario · viernes 09:00", steps: ["NovaContent", "Aprobación editorial", "Programación"], departmentId: "dist", active: true },
  { id: "w4", name: "Consolidación de costos", trigger: "Horario · diario 06:00", steps: ["LedgerBot", "Alertas"], departmentId: "fin", active: true },
  { id: "w5", name: "Auditoría de data room", trigger: "Manual", steps: ["ExitPrep", "Checklist", "Reporte"], departmentId: "exit", active: false },
];
