import type { Product } from "@/types";

export const products: Product[] = [
  {
    id: "app-01",
    code: "APP 01",
    name: "Lumen Retail",
    description: "Plataforma de analítica predictiva para retail independiente.",
    stage: "desarrollo",
    progress: 78,
    techStatus: "Build estable · 3 issues abiertos",
    commercialStatus: "12 pilotos firmados",
    owner: "Joshua R. García",
    ownerRole: "CEO / Fundador",
    nextMilestone: "Cierre de beta cerrada",
    launchDate: "15 ago 2026",
    risk: "medio",
    health: "saludable",
    country: "México",
    businessModel: "SaaS B2B",
    priority: "alta",
    status: "activo",
    exitReady: false,
    healthScore: 82,
    mrr: 2450,
    users: 386,
    monthlyCost: 740,
    accent: "blue",
    market: {
      tam: "1.2 B USD",
      sam: "84 M USD",
      competitors: ["Retailytics", "ShopSense", "Dataret"],
      differentiation: "Predicción de inventario con datos de punto de venta locales.",
    },
    tech: { stack: ["React", "TypeScript", "Postgres", "Python"], coverage: 71, uptime: 99.4, openIssues: 3 },
    design: { system: "Lumen DS v0.8", screens: 42, pending: 6 },
    distribution: { channels: ["LinkedIn", "Newsletter", "Partners"], waitlist: 412, contentPieces: 18 },
    finance: { revenue: 2450, costs: 740, margin: 69 },
    risks: [
      { id: "r1", label: "Dependencia de un integrador de POS", level: "medio", mitigation: "Segundo conector en desarrollo." },
      { id: "r2", label: "Cobertura de pruebas por debajo del objetivo", level: "medio", mitigation: "Sprint de QA asignado." },
    ],
    documents: [
      { id: "d1", name: "Especificación de producto", type: "PDF", updatedAt: "12 ago 2026" },
      { id: "d2", name: "Modelo financiero", type: "XLSX", updatedAt: "10 ago 2026" },
      { id: "d3", name: "Arquitectura técnica", type: "MD", updatedAt: "08 ago 2026" },
    ],
    history: [
      { id: "h1", date: "16 ago 2026", label: "Módulo de autenticación SSO desplegado", author: "CodePilot" },
      { id: "h2", date: "14 ago 2026", label: "Fase actualizada a Desarrollo", author: "Joshua R. García" },
      { id: "h3", date: "09 ago 2026", label: "Reporte de mercado Q3 generado", author: "MarketMind" },
    ],
    metricsSeries: [
      { label: "Mar", usuarios: 40, ingresos: 320 },
      { label: "Abr", usuarios: 96, ingresos: 640 },
      { label: "May", usuarios: 148, ingresos: 980 },
      { label: "Jun", usuarios: 232, ingresos: 1480 },
      { label: "Jul", usuarios: 305, ingresos: 1960 },
      { label: "Ago", usuarios: 386, ingresos: 2450 },
    ],
  },
  {
    id: "app-02",
    code: "APP 02",
    name: "Atenea Support",
    description: "Asistente inteligente para atención al cliente en pymes.",
    stage: "validacion",
    progress: 54,
    techStatus: "Prototipo funcional",
    commercialStatus: "28 entrevistas de validación",
    owner: "Ana García",
    ownerRole: "Directora de distribución",
    nextMilestone: "Validación de precio con 10 clientes",
    launchDate: "22 sep 2026",
    risk: "alto",
    health: "atencion",
    country: "España",
    businessModel: "SaaS PLG",
    priority: "alta",
    status: "activo",
    exitReady: false,
    healthScore: 64,
    mrr: 890,
    users: 142,
    monthlyCost: 610,
    accent: "violet",
    market: {
      tam: "740 M USD",
      sam: "52 M USD",
      competitors: ["HelpLoop", "Kustom", "Replay AI"],
      differentiation: "Configuración en 15 minutos sin equipo técnico.",
    },
    tech: { stack: ["React", "TypeScript", "Node", "Postgres"], coverage: 48, uptime: 98.7, openIssues: 9 },
    design: { system: "Atenea DS v0.4", screens: 26, pending: 11 },
    distribution: { channels: ["YouTube faceless", "TikTok", "Comunidad"], waitlist: 268, contentPieces: 31 },
    finance: { revenue: 890, costs: 610, margin: 31 },
    risks: [
      { id: "r1", label: "Precio no validado en el mercado objetivo", level: "alto", mitigation: "Entrevistas de precio en curso." },
      { id: "r2", label: "Costo por conversación de IA elevado", level: "medio", mitigation: "Prueba con modelo más económico." },
    ],
    documents: [
      { id: "d1", name: "Guion de entrevistas", type: "DOC", updatedAt: "15 ago 2026" },
      { id: "d2", name: "Análisis competitivo", type: "PDF", updatedAt: "11 ago 2026" },
    ],
    history: [
      { id: "h1", date: "15 ago 2026", label: "Cohorte de entrevistas cerrada", author: "InsightAI" },
      { id: "h2", date: "07 ago 2026", label: "Presupuesto de marketing solicitado", author: "GrowthOps" },
    ],
    metricsSeries: [
      { label: "Mar", usuarios: 8, ingresos: 0 },
      { label: "Abr", usuarios: 22, ingresos: 120 },
      { label: "May", usuarios: 48, ingresos: 280 },
      { label: "Jun", usuarios: 76, ingresos: 450 },
      { label: "Jul", usuarios: 112, ingresos: 690 },
      { label: "Ago", usuarios: 142, ingresos: 890 },
    ],
  },
  {
    id: "app-03",
    code: "APP 03",
    name: "Verda Trace",
    description: "Plataforma de sostenibilidad y trazabilidad para agroexportadores.",
    stage: "diseno",
    progress: 32,
    techStatus: "Arquitectura definida",
    commercialStatus: "3 cartas de intención",
    owner: "Joshua R. García",
    ownerRole: "CEO / Fundador",
    nextMilestone: "Prototipo navegable completo",
    launchDate: "10 nov 2026",
    risk: "bajo",
    health: "saludable",
    country: "Colombia",
    businessModel: "SaaS + servicios",
    priority: "media",
    status: "activo",
    exitReady: false,
    healthScore: 71,
    mrr: 0,
    users: 0,
    monthlyCost: 320,
    accent: "green",
    market: {
      tam: "480 M USD",
      sam: "31 M USD",
      competitors: ["TraceOne", "AgroChain"],
      differentiation: "Cumplimiento normativo europeo listo para exportadores LATAM.",
    },
    tech: { stack: ["React", "TypeScript", "Postgres"], coverage: 22, uptime: 100, openIssues: 1 },
    design: { system: "Verda DS v0.2", screens: 14, pending: 18 },
    distribution: { channels: ["Eventos", "Alianzas", "LinkedIn"], waitlist: 96, contentPieces: 7 },
    finance: { revenue: 0, costs: 320, margin: -100 },
    risks: [
      { id: "r1", label: "Requisitos regulatorios en evolución", level: "medio", mitigation: "Revisión legal trimestral." },
    ],
    documents: [
      { id: "d1", name: "Marco regulatorio EUDR", type: "PDF", updatedAt: "13 ago 2026" },
      { id: "d2", name: "Mapa de flujos de diseño", type: "FIG", updatedAt: "16 ago 2026" },
    ],
    history: [
      { id: "h1", date: "16 ago 2026", label: "Sistema de diseño inicial aprobado", author: "Joshua R. García" },
      { id: "h2", date: "05 ago 2026", label: "Investigación regulatoria completada", author: "DataScout" },
    ],
    metricsSeries: [
      { label: "Mar", usuarios: 0, ingresos: 0 },
      { label: "Abr", usuarios: 0, ingresos: 0 },
      { label: "May", usuarios: 0, ingresos: 0 },
      { label: "Jun", usuarios: 0, ingresos: 0 },
      { label: "Jul", usuarios: 0, ingresos: 0 },
      { label: "Ago", usuarios: 0, ingresos: 0 },
    ],
  },
];
